spring:
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    generate-ddl: false
    open-in-view: true
  datasource:
    url: "jdbc:postgresql://db-tp-pg:5432/db"
    username: usr
    password: pwd
    driver-class-name: org.postgresql.Driver
    hikari: 
      initialization-fail-timeout: 0